import tensorflow as tf


user_keys = [
    'x_29',
    'x_47',
]  # not found in features_dict


features_dict = {
    # var len
    # user fea
    'x_107': tf.VarLenFeature(dtype=tf.int64),
    'x_110': tf.VarLenFeature(dtype=tf.int64),
    'x_113': tf.VarLenFeature(dtype=tf.int64),
    'x_116': tf.VarLenFeature(dtype=tf.int64),
    'x_119': tf.VarLenFeature(dtype=tf.int64),
    'x_12': tf.VarLenFeature(dtype=tf.int64),
    'x_122': tf.VarLenFeature(dtype=tf.int64),
    'x_131': tf.VarLenFeature(dtype=tf.int64),
    'x_72': tf.VarLenFeature(dtype=tf.int64),
    'x_73': tf.VarLenFeature(dtype=tf.int64),
    # item fea
    'x_136': tf.VarLenFeature(dtype=tf.int64),
    'x_137': tf.VarLenFeature(dtype=tf.int64),
    'x_156': tf.VarLenFeature(dtype=tf.int64),
    'x_157': tf.VarLenFeature(dtype=tf.int64),
    'x_158': tf.VarLenFeature(dtype=tf.int64),
    'x_159': tf.VarLenFeature(dtype=tf.int64),
    'x_160': tf.VarLenFeature(dtype=tf.int64),
    'x_161': tf.VarLenFeature(dtype=tf.int64),
    'x_162': tf.VarLenFeature(dtype=tf.int64),
    'x_163': tf.VarLenFeature(dtype=tf.int64),
    'x_164': tf.VarLenFeature(dtype=tf.int64),
    'x_165': tf.VarLenFeature(dtype=tf.int64),
    'x_285': tf.VarLenFeature(dtype=tf.int64),
    'x_286': tf.VarLenFeature(dtype=tf.int64),
    'x_287': tf.VarLenFeature(dtype=tf.int64),
    'x_288': tf.VarLenFeature(dtype=tf.int64),
    'x_289': tf.VarLenFeature(dtype=tf.int64),
    'x_290': tf.VarLenFeature(dtype=tf.int64),
    'x_291': tf.VarLenFeature(dtype=tf.int64),
    'x_292': tf.VarLenFeature(dtype=tf.int64),
    'x_62': tf.VarLenFeature(dtype=tf.int64),
    'x_63': tf.VarLenFeature(dtype=tf.int64),
    'x_67': tf.VarLenFeature(dtype=tf.int64),
    'x_71': tf.VarLenFeature(dtype=tf.int64),


    # fix seq len
    # user fea
    'x_293': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=0),
    'x_294': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=0),
    'x_295': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=0),
    'x_296': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=0),
    'x_297': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=0),
    'x_298': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=0),
    'x_299': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=0),
    'xis_impr_133': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=None),
    'xis_impr_143': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=None),
    'xis_impr_229': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=None),
    'xis_impr_230': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=None),
    'xis_impr_231': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=None),
    'xis_impr_232': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=None),
    # item fea
    'x2_171': tf.FixedLenSequenceFeature(shape=[], dtype=tf.float32, allow_missing=True, default_value=None),
    'x2_172': tf.FixedLenSequenceFeature(shape=[], dtype=tf.float32, allow_missing=True, default_value=None),
    'x2_195': tf.FixedLenSequenceFeature(shape=[], dtype=tf.float32, allow_missing=True, default_value=None),
    'x2_306': tf.FixedLenSequenceFeature(shape=[], dtype=tf.float32, allow_missing=True, default_value=None),
    'x2_307': tf.FixedLenSequenceFeature(shape=[], dtype=tf.float32, allow_missing=True, default_value=None),
    'xis_bias_233': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=None),
    'xis_bias_234': tf.FixedLenSequenceFeature(shape=[], dtype=tf.int64, allow_missing=True, default_value=None),

    # fix len
    # user fea
    'NatureSearchMark': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=2),
    'ads_pos': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'search_impr_listwise_mask_impr': tf.FixedLenFeature(shape=[1000], dtype=tf.int64, default_value=None),
    'search_impr_listwise_pooling_ratio_impr': tf.FixedLenFeature(shape=[50], dtype=tf.float32, default_value=None),
    'session_mask': tf.FixedLenFeature(shape=[75], dtype=tf.int64, default_value=None),
    'session_pooling_ratio': tf.FixedLenFeature(shape=[25], dtype=tf.float32, default_value=None),
    'session_size': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=None),
    'x_1': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_11': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_101': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_102': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_103': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_104': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_125': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_126': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_127': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_139': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_14': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_143': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_17': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_196': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_197': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_198': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_199': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_200': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_201': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_202': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_203': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_204': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_205': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_206': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_207': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_208': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_209': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_300': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_314': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_315': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_330': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_332': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_333': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_55': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_56': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_57': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_58': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_6': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_7': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_74': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_75': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_8': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_81': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_82': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_83': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_84': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_85': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_86': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_87': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_88': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_89': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_9': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'xs_132': tf.FixedLenFeature(shape=[75], dtype=tf.int64, default_value=None),
    'xs_133': tf.FixedLenFeature(shape=[75], dtype=tf.int64, default_value=None),
    'xs_134': tf.FixedLenFeature(shape=[75], dtype=tf.int64, default_value=None),
    'xs_135': tf.FixedLenFeature(shape=[75], dtype=tf.int64, default_value=None),
    'xs_138': tf.FixedLenFeature(shape=[75], dtype=tf.int64, default_value=None),
    'xs_143': tf.FixedLenFeature(shape=[75], dtype=tf.int64, default_value=None),
    'xs_166': tf.FixedLenFeature(shape=[75], dtype=tf.int64, default_value=None),
    'xs_167': tf.FixedLenFeature(shape=[75], dtype=tf.int64, default_value=None),
    'xs_168': tf.FixedLenFeature(shape=[75], dtype=tf.int64, default_value=None),
    'xs_169': tf.FixedLenFeature(shape=[75], dtype=tf.int64, default_value=None),
    'xs_170': tf.FixedLenFeature(shape=[75], dtype=tf.int64, default_value=None),
    # item
    'extra_info': tf.FixedLenFeature(shape=[], dtype=tf.string, default_value='0#0#0'),
    'past_preds': tf.FixedLenFeature(shape=[], dtype=tf.float32, default_value=0.0),
    'rt_clk_133': tf.FixedLenFeature(shape=[20], dtype=tf.int64, default_value=None),
    'rt_clk_138': tf.FixedLenFeature(shape=[20], dtype=tf.int64, default_value=None),
    'rt_clk_228': tf.FixedLenFeature(shape=[20], dtype=tf.int64, default_value=None),
    'rt_clk_229': tf.FixedLenFeature(shape=[20], dtype=tf.int64, default_value=None),
    'rt_clk_230': tf.FixedLenFeature(shape=[20], dtype=tf.int64, default_value=None),
    'rt_clk_231': tf.FixedLenFeature(shape=[20], dtype=tf.int64, default_value=None),
    'rt_clk_mask': tf.FixedLenFeature(shape=[20], dtype=tf.int64, default_value=None),
    'rt_impr_133': tf.FixedLenFeature(shape=[50], dtype=tf.int64, default_value=None),
    'rt_impr_138': tf.FixedLenFeature(shape=[50], dtype=tf.int64, default_value=None),
    'rt_impr_228': tf.FixedLenFeature(shape=[50], dtype=tf.int64, default_value=None),
    'rt_impr_229': tf.FixedLenFeature(shape=[50], dtype=tf.int64, default_value=None),
    'rt_impr_230': tf.FixedLenFeature(shape=[50], dtype=tf.int64, default_value=None),
    'rt_impr_231': tf.FixedLenFeature(shape=[50], dtype=tf.int64, default_value=None),
    'rt_impr_mask': tf.FixedLenFeature(shape=[50], dtype=tf.int64, default_value=None),
    'x_10': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_100': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_105': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_106': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_108': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_111': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_114': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_117': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_120': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_123': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_124': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_128': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_129': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_130': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_141': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_144': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_145': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_146': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_147': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_148': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_149': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_15': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_150': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_151': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_152': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_153': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_154': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_155': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_16': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_173': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_174': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_175': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_176': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_178': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_179': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_180': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_181': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_182': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_183': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_184': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_185': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_2': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_210': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_211': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_224': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_225': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_25': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_26': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_260': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_261': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_262': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_263': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_264': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_265': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_266': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_267': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_268': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_269': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_27': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_270': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_271': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_272': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_273': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_274': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_275': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_276': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_277': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_278': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_279': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_280': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_281': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_282': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_283': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_284': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_30': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_301': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_302': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_303': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_304': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_305': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_31': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_310': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_311': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_312': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_313': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_316': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_317': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_318': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_319': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_32': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_320': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_321': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_322': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_323': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_324': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_325': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_326': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_327': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_328': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_329': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_33': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_331': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_334': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_335': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_336': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_337': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_338': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_339': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_34': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_340': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_341': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_35': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_36': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_37': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_38': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_39': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_4': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_40': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_41': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_5': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_59': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_60': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_61': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_64': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_65': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_66': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_68': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_69': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_70': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_76': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_77': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_78': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_79': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_80': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_90': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_91': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_92': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_93': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_94': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_95': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_96': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_97': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_98': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'x_99': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'xs_session_geo5_bias': tf.FixedLenFeature(shape=[25], dtype=tf.int64, default_value=None),
    'xs_session_loca_bias': tf.FixedLenFeature(shape=[25], dtype=tf.int64, default_value=None),
    'xs_session_poi_bias': tf.FixedLenFeature(shape=[25], dtype=tf.int64, default_value=None),
    'xs_session_poi_num': tf.FixedLenFeature(shape=[25], dtype=tf.int64, default_value=None),
    'xs_session_type2_bias': tf.FixedLenFeature(shape=[25], dtype=tf.int64, default_value=None),
    'xs_session_type_bias': tf.FixedLenFeature(shape=[25], dtype=tf.int64, default_value=None),
    'y_amt': tf.FixedLenFeature(shape=[], dtype=tf.float32, default_value=0.0),
    'y_call': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'y_ctr': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=1),
    'y_cvr': tf.FixedLenFeature(shape=[], dtype=tf.float32, default_value=1.0),
    'y_cvr_prob': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=1),
    'y_daodian': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'y_favor': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'y_order_book': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'y_payamt': tf.FixedLenFeature(shape=[], dtype=tf.float32, default_value=0.0),
    'y_paycvr': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=1),
    'y_share': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'y_wedchat': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0),
    'y_wedchat_send_msg': tf.FixedLenFeature(shape=[], dtype=tf.int64, default_value=0)
}


def parse_func(example_proto):
    return tf.parse_single_example(example_proto, features_dict)


def inspect_tf_record(fname):
    # ds
    ds = tf.data.TFRecordDataset(fname)
    ds = ds.map(parse_func)
    # iter
    ds_iter = ds.make_one_shot_iterator()
    next_element = ds_iter.get_next()

    cnt = 0
    with tf.Session() as sess:
        try:
            for i in range(1000):
                ret = sess.run(next_element)

                cnt += 1
        except Exception as e:
            print(e)
    print("ele num", cnt)


if __name__ == "__main__":
    import sys
    fname = sys.argv[1]
    inspect_tf_record(fname)
